### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by BillSheikh1** [Paul-Ladyman/dnd-battle-tracker#34]
App should work on mobile

(currently can't search for creature on mobile)

**Comment by Paul-Ladyman** [comment]
It does seem to be possible to tap the magnifying glass icon to search for a creature on mobile, though the tap-able area seems to be very small and it takes a few goes to find it! I can get this to work on an actual mobile device but haven't been able to in Chrome's mobile dev view.

**Comment by Paul-Ladyman** [comment]
Being addressed in https://github.com/Paul-Ladyman/dnd-battle-tracker/pull/35.

**Comment by Paul-Ladyman** [comment]
Fix deployed! Thanks Bill!
