### ISSUE TITLE
Initiative Improvements

### ISSUE THREAD

**Issue by Paul-Ladyman** [Paul-Ladyman/dnd-battle-tracker#435]
- The term "turn" should be used instead of "initiative" when referring to which creature's turn it is. For example in the Battle Toolbar
- The name of the creature who's turn it is should be a anchor link to that creature in the list

**Comment by vforvasile** [comment]
I think I covered the 2nd one in a [commit](https://github.com/vforvasile/dnd-battle-tracker/commit/600912e260aa15e1747868873c3a66ec61dab5d3) in my fork, if you meant click on the header creature whose turn is it and scroll to it in the list.
